# shared/acq_shared/store.py
"""Store Protocol — defines the behavioral contract for all store backends."""

from __future__ import annotations

from typing import Protocol

from acq_shared.models import Answer, Comment, Question, Tag, Vote


class Store(Protocol):
    """Repository interface for Q&A storage.

    Two implementations exist: SqliteStore (local, FTS5) and PostgresStore
    (team API, tsvector/GIN). Both must pass the shared test suite in
    tests/test_store_contract.py.
    """

    def create_question(self, question: Question, tag_names: list[str]) -> Question: ...
    def get_question(self, question_id: str) -> Question | None: ...
    def get_question_thread(self, question_id: str) -> dict | None: ...
    def edit_question(
        self, question_id: str, new_body: str, edited_by: str, edited_by_type: str
    ) -> Question | None: ...
    def pin_answer(self, question_id: str, answer_id: str) -> Question | None: ...
    def unpin_answer(self, question_id: str) -> Question | None: ...
    def create_answer(self, answer: Answer) -> Answer: ...
    def get_answer(self, answer_id: str) -> Answer | None: ...
    def edit_answer(self, answer_id: str, new_body: str, edited_by: str, edited_by_type: str) -> Answer | None: ...
    def create_comment(self, comment: Comment) -> Comment: ...
    def cast_vote(self, vote: Vote) -> dict: ...
    def search(
        self,
        query: str,
        tags: list[str] | None = None,
        language: str | None = None,
        framework: str | None = None,
        limit: int = 10,
    ) -> list[dict]: ...
    def find_similar_questions(self, title: str, tag_names: list[str]) -> list[dict]: ...
    def get_or_create_tag(self, name: str) -> Tag: ...
    def list_tags(self, q: str | None = None) -> list[Tag]: ...
    def get_status(self) -> dict: ...
    def approve_content(self, content_id: str) -> bool: ...
    def reject_content(self, content_id: str) -> bool: ...
    def pending_queue(self) -> dict: ...
    def get_question_history(self, question_id: str) -> list: ...
    def get_answer_history(self, answer_id: str) -> list: ...
    def merge_tags(self, source_id: str, target_id: str) -> None: ...
    def create_user(self, username: str, password_hash: str) -> None: ...
    def get_user(self, username: str) -> dict | None: ...
    def export_since(self, since: str | None = None) -> dict: ...
    def bulk_upsert(self, data: dict) -> int: ...
    def close(self) -> None: ...
