# shared/acq_shared/store.py
"""Store Protocol — defines the behavioral contract for all store backends."""

from __future__ import annotations

from typing import Literal, Protocol

from acq_shared.models import Answer, Comment, Question, Tag, Vote


class Store(Protocol):
    """Repository interface for Q&A storage.

    Two implementations exist: SqliteStore (local, FTS5) and PostgresStore
    (team API, tsvector/GIN). Both must pass the shared test suite in
    tests/test_store_contract.py.
    """

    def create_question(self, question: Question, tag_names: list[str]) -> Question: ...
    def get_question(self, question_id: str) -> Question | None: ...
    def get_question_thread(
        self, question_id: str, include_pending: bool = False, include_deleted: bool = False
    ) -> dict | None: ...
    def edit_question(
        self,
        question_id: str,
        new_body: str | None,
        edited_by: str,
        edited_by_type: Literal["agent", "human"],
        new_title: str | None = None,
        new_tags: list[str] | None = None,
    ) -> Question | None: ...
    def pin_answer(self, question_id: str, answer_id: str) -> Question | None: ...
    def unpin_answer(self, question_id: str) -> Question | None: ...
    def create_answer(self, answer: Answer) -> Answer: ...
    def get_answer(self, answer_id: str) -> Answer | None: ...
    def edit_answer(
        self, answer_id: str, new_body: str, edited_by: str, edited_by_type: Literal["agent", "human"]
    ) -> Answer | None: ...
    def create_comment(self, comment: Comment) -> Comment: ...
    def get_comment(self, comment_id: str) -> Comment | None: ...
    def edit_comment(
        self, comment_id: str, new_body: str, edited_by: str, edited_by_type: Literal["agent", "human"]
    ) -> Comment | None: ...
    def get_comment_history(self, comment_id: str) -> list: ...
    def cast_vote(self, vote: Vote) -> dict: ...
    def delete_vote(self, target_id: str, voter_id: str, voter_type: str) -> bool: ...
    def get_user_votes(self, voter_id: str, voter_type: str, target_ids: list[str]) -> dict[str, int]: ...
    def search(
        self,
        query: str,
        tags: list[str] | None = None,
        language: str | None = None,
        framework: str | None = None,
        limit: int = 10,
    ) -> list[dict]: ...
    def find_similar_questions(self, title: str, tag_names: list[str]) -> list[dict]: ...
    def get_or_create_tag(self, name: str) -> Tag: ...
    def list_tags(self, q: str | None = None) -> list[Tag]: ...
    def get_status(self) -> dict: ...
    # Moderation resolves question, answer, and comment ids alike. Approving a
    # new pending question also promotes its bundled answers. Approving a
    # deleted question only restores that question, so pending answers under it
    # return to the ordinary review queue rather than being silently published.
    def approve_content(self, content_id: str) -> bool | None: ...
    def reject_content(self, content_id: str) -> bool | None: ...

    def pending_queue(self) -> dict:
        """Return {"questions": [Question], "answers": [Answer], "comments": [Comment]}.

        All three lists hold only pending items, oldest first. Answers and
        comments are additionally filtered on parent liveness, so nothing under
        a pending or rejected question is ever offered as a standalone card.
        """
        ...

    def list_questions(
        self,
        status: str | None = None,
        tag: str | None = None,
        offset: int = 0,
        limit: int = 20,
    ) -> tuple[list[dict], int]: ...
    def get_question_history(self, question_id: str) -> list: ...
    def get_answer_history(self, answer_id: str) -> list: ...
    def merge_tags(self, source_id: str, target_id: str) -> None: ...
    def create_user(self, username: str, password_hash: str) -> None: ...
    def get_user(self, username: str) -> dict | None: ...
    def create_agent_key(self, api_key: str, agent_name: str, github_username: str) -> dict: ...
    def get_agent_key(self, api_key: str) -> dict | None: ...
    def get_agent_key_by_github(self, github_username: str) -> dict | None: ...
    def export_since(self, since: str | None = None) -> dict: ...
    def bulk_upsert(self, data: dict) -> int: ...
    def close(self) -> None: ...
